global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: yt_web
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:48333"]
        labels:
          service: web

  - job_name: yt_worker
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:48410"]
        labels:
          service: worker
